force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
                <label>Read/Write</label>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Application_To_Objects__c.field-meta.xml
<CustomField>
    <fullName>Application_To_Objects__c</fullName>
    <label>Application To Objects</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenericGroupDelete.cls
public with sharing class GenericGroupDelete implements Queueable  {
    private Map<Id,Team__c> objectData;

    public GenericGroupDelete(Map<Id,Team__c> data){
        this.objectData = data;
    }

    public void execute(System.QueueableContext qc){

        List<String> groupNames = new List<string>();
        set<Id> teamIds = new set<Id>();

        system.debug('Team Id: ' + objectData);

        for (Team__c oTeam : [Select Id,Type__c,Application_To_Objects__c,Account__c,Name,Access_Level__c,Account__r.Name from Team__C where Id IN :objectData.keySet() ALL ROWS]){
            string groupName=oteam.Application_To_Objects__c+oteam.name+oteam.Account__r.Name;
            groupNames.add(groupName);
        }
        list<Group> groupsToDelete = [Select Id,Name From Group Where Name IN :groupNames ];

        if(groupsToDelete?.size()>0){
            delete groupsToDelete;
        }
    }
}